#rll_cell:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 1000

  # Trajectory Controllers --------------------------------------
  #
  # Forward Position Controllers --------------------------------
  PositionJointInterface_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - $(arg robot_name)_joint_1
      - $(arg robot_name)_joint_2
      - $(arg robot_name)_joint_3
      - $(arg robot_name)_joint_4
      - $(arg robot_name)_joint_5
      - $(arg robot_name)_joint_6
      - $(arg robot_name)_joint_7

    constraints:
      goal_time: 2.0                   # Override default
      stopped_velocity_tolerance: 0.03

    state_publish_rate:  1000            # Override default
    action_monitor_rate: 30            # Override default
    stop_trajectory_duration: 0.5        # Override default

  # Gripper controller ------------------------------------------
  PositionJointInterface_gripper_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - $(arg robot_name)_egl_position_left
      - $(arg robot_name)_egl_position_right
    gains:
      $(arg robot_name)_egl_position_left: {p: 500,  d: 10, i: 2, i_clamp: 10}
      $(arg robot_name)_egl_position_right: {p: 500,  d: 10, i: 2, i_clamp: 10}
    constraints:
      goal_time: 0.5
      stopped_velocity_tolerance: 0.03
      $(arg robot_name)_egl_position_left:
        goal: 0.04
      $(arg robot_name)_egl_position_right:
        goal: 0.04
